targets:
  $default:
    builders:
      artemis:
        options:
          schema_mapping:
            - output: lib/api/graphql/generated/user.api.dart
              schema: lib/api/graphql/schema.graphql
              queries_glob: lib/api/graphql/query/get_login.graphql
            - output: lib/api/graphql/generated/repo_list.api.dart
              schema: lib/api/graphql/schema.graphql
              queries_glob: lib/api/graphql/query/repo_list.graphql
